### PR TITLE
Added Vite Support

### PR DESCRIPTION
**Pull request by pratik227**
Added Vite Support

https://github.com/quasarframework/quasar/discussions/13919

### CODE REVIEW

**Comment by dragonballa** [comment]
Fantastic! is there a way to pull from this branch when i do `quasar add ext firebase` ?

**Comment by pratik227** [comment]
I think you need to checkout this branch and then publish package from this branch

**Comment by dragonballa** [comment]
can you explain by publish package? on quasar?

**Comment by pratik227** [comment]
So basically what I get is you are not planning to merge this PR but you want that we user run quasar ext add quasar-ui-firebase it uses this branch correct? Correct me if I'm wrong.

So you can fetch this branch you need to go to app-extension folder and just publish the app-extension and then when user run this command then it will work.

**Comment by dragonballa** [comment]
yes correct. thank you will give this a go!

**Comment by ldiebold** [comment]
Will merge this in, though I recommend using [VueAuth](https://quasar.vueauth.com/) as this repo will no longer be worked on.

```js
quasar ext add @vueauth/auth
```

VueAuth basically unifies authentication across all providers!

**Pull request merged**
